# Generated by Django 6.0 on 2026-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
