# Generated by Django 6.0 on 2026-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_offerposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blouse_piece',
            field=models.BooleanField(default=True, help_text='Blouse piece included'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, help_text='e.g., Silk, Cotton, Chiffon', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, help_text='e.g., 5.5 meters', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, help_text='e.g., Wedding, Festival, Casual', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wash_care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='work',
            field=models.CharField(blank=True, help_text='e.g., Zari, Embroidery, Print', max_length=100, null=True),
        ),
    ]
