# Generated by Django 5.2.5 on 2026-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerposter',
            name='mobile_image',
            field=models.FileField(blank=True, help_text='Optional portrait/phone-optimized image shown on mobile screens.', null=True, upload_to='posters/mobile/'),
        ),
    ]
