# Generated by Django 6.0 on 2026-03-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_offer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='posters/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
